### PR TITLE
Actually do this and also I updated yarn mappings 

### PR DESCRIPTION
**Pull request by DarkReaper231**
Do branches like all sentient people instead of making folders in repo lmao

### CODE REVIEW

**Comment by DarkReaper231** [comment]
Btw the build checks will have to be reworked cuz those folders no longer exist

**Comment by DarkReaper231** [comment]
Okay I edited them so here you go. I made your repo look slightly less dumb.

**Comment by DarkReaper231** [comment]
Also for other versions pls just make branches like I did in my fork.

**Comment by DarkReaper231** [comment]
I am switching to epearl so gl mate.

**Comment by feliscatusmeows** [comment]
ya this is dead :(((((( @BleachDrinker420 wake up pls

**Pull request closed without merging**
