### PR TITLE
Some bugfixes and new features.

### PR DESCRIPTION
**Pull request by DevScyu**
New Features:

SafeWalk
AutoWalk
MaintainAltitude - Basically presses space once your Y goes below a certain value and stops once it reaches it (Similar to #62)
ElytraReplace - Replaces broken elytras in chest slot with non-broken elytras in inventory and resumes flying (useful when used with AutoWalk and MaintainAltitude)

Password Field now hides the characters.

Password is now encrypted in logins.txt

Bug Fixes:

Fixed some display bugs with the scraper/cleanup/protocol buttons, and window Z positioning (still some slight bugs with certain texts, but no longer interferes with the title for example)

### CODE REVIEW

**Comment by BleachDrinker420** [comment]
The password box seems like extreme overkill ot recreate the entire class, just extend TextFieldWidget and override a few methods.
All the modules seems good, except MaintainAltitude, its kinda meh to have an entire module for that, so remove that for now, i'll fix the elytrafly eventually.
Elytrafly has an unnecessary onDisable()
And please alphabeticaly sort the mixin and module list.

Update me when thats done and if its good you can copy paste the code to 1.14 and 1.16

**Comment by BleachDrinker420** [comment]
also revert the static import on the title screen, static imports is a sin

**Comment by DevScyu** [comment]
> also revert the static import on the title screen, static imports is a sin

Sorry my ide messed up and kept saying it was an error

**Comment by DevScyu** [comment]
> The password box seems like extreme overkill to recreate the entire class, just extend TextFieldWidget and override a few methods.
@BleachDrinker420 

All of the TextFieldWidget class uses private vars so I can't just extend and override.

**Comment by BleachDrinker420** [comment]
what did you change in the custom textbox? because with that much copied directly from minecraft its gonna be a pain to update it every new update and if the mappings change some of the methods could stop working and i would have no idea

**Comment by DevScyu** [comment]
> what did you change in the custom textbox? because with that much copied directly from minecraft its gonna be a pain to update it every new update and if the mappings change some of the methods could stop working and i would have no idea

Honestly, it's just a very small `.replaceAll(".", "\u2022")` in the render method, and changing some of the keybinds to not allow Copy/Cut from the password box.

I've also just noticed the "BleachCipher" class, which I totally missed before implementing my own Decryption class.

**Comment by BleachDrinker420** [comment]
ah, just delete that class, it was my attempt at ""Encryption""

**Comment by DevScyu** [comment]
Added AutoTool #61

**Comment by BleachDrinker420** [comment]
skidding from wurst iskinda cringe, but ok
most of the commits are ok i guess, except the last "Add Trajectories" one, so much random junk trown and skidded code thrown in, and added random star imports, not ok, i would suggest just reverting that commit, then maybe i can merge it

**Comment by BleachDrinker420** [comment]
also here is the simplified password box
[passfieldwidget.txt](https://github.com/BleachDrinker420/bleachhack-1.14/files/4910775/passfieldwidget.txt)

**Comment by BleachDrinker420** [comment]
actually, fuck it, merge, i'll do the rest

**Pull request merged**
