### PR TITLE
[Outdated] Searchfunction for the gui

### PR DESCRIPTION
**Pull request by lasnikprogram**
A small text box on the top left when opening the (RIGHT-SHIFT) GUI.
If it found the module the module will be marked as red.
(Sorry for the ugly view in code section... My IDE formatted it)
This should work with every Bleachhack version...
Preview Image

### CODE REVIEW

**Comment by lasnikprogram** [comment]
Could have messed something up. I was pretty tired XD

**Comment by BleachDrinker420** [comment]
update to the latest commit, then add this to a setting in the clickgui module, then i will merge

**Comment by lasnikprogram** [comment]
How can I update without deleting my changes?

**Comment by BleachDrinker420** [comment]
image
not sure if it works on forks tho

**Comment by lasnikprogram** [comment]
I think you have a custom plugin. I only have like two options

**Pull request closed without merging**
