### PR TITLE
HAIIII

### PR DESCRIPTION
**Pull request by d1gress**
HAI PULL PLEAS ALSO FIX ALL THE SETTINGS YOURSELF HAHA IM TOO LAZY

### CODE REVIEW

**Comment by d1gress** [comment]
fuck you codacy

**Comment by BleachDrinker420** [comment]
no swearing on this christian block game github

**Comment by d1gress** [comment]
merge it

**Comment by BleachDrinker420** [comment]
its like 20 commits behind, its break everything

**Comment by BleachDrinker420** [comment]
it will*

**Comment by d1gress** [comment]
fix yourself nerd

**Comment by BleachDrinker420** [comment]
no
🦀🦀🦀🦀🦀

**Pull request closed without merging**
